[package]
name = "rls"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
chrono = "0.4.42"
colored = "3.0.0"
users = "0.11.0"
humansize = "2.1.3"
term_size = "0.3.2"
