name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    name: Release - \${{ matrix.platform.os_name }}
    strategy:
      matrix:
        platform:
          - os_name: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: rls
            name: rls-linux-amd64
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: rls.exe
            name: rls-windows-amd64.exe
          - os_name: macOS-x86_64
            os: macos-latest
            target: x86_64-apple-darwin
            bin: rls
            name: rls-macos-amd64

    runs-on: \${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: \${{ matrix.platform.target }}
          args: "--release --locked"
          strip: true

      - name: Rename binary (linux/mac)
        if: matrix.platform.os_name != 'Windows-x86_64'
        run: mv target/\${{ matrix.platform.target }}/release/\${{ matrix.platform.bin }} target/\${{ matrix.platform.target }}/release/\${{ matrix.platform.name }}

      - name: Rename binary (windows)
        if: matrix.platform.os_name == 'Windows-x86_64'
        run: mv target/\${{ matrix.platform.target }}/release/\${{ matrix.platform.bin }} target/\${{ matrix.platform.target }}/release/\${{ matrix.platform.name }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/\${{ matrix.platform.target }}/release/\${{ matrix.platform.name }}